### ISSUE TITLE
Event forwarding stopped working after upgrading to 5.44.2

### ISSUE THREAD

**Issue by ericntd** [mparticle-integrations/mparticle-android-integration-appsflyer#63]
**Version**
We were using 5.35.2 and it was working
We also tried and 5.45.0 is not working either
Install referrer version 2.2 (upgraded from 1.1) if that matters
Android versions
```
        buildTools: "29.0.2",
        compileSdk: 32, // we upgraded from 31 in the same release where we upgraded your kit from 5.35.2  to 5.44.2
        minSdk    : 25,
        targetSdk : 32, // we upgraded from 31 in the same release where we upgraded your kit from 5.35.2  to 5.44.2
```
Could the kit be incompatible with Android SDK 32 for some reason?

There is 1 error logged which may or may not be relevant but there's no stacktrace to it:
```
2022-10-24 16:14:43.948 30695-30695/com.our E/MParticleManager: Exception while starting kit 92: Parameter specified as non-null is null: method kotlin.jvm.internal.Intrinsics.checkNotNullParameter, parameter bundle
```
I've tried the debugging techniques [here](https://docs.mparticle.com/developers/sdk/android/logger/) but stacktrace was not revealed either
Nor there was any additional logs to what's happening

**Comment by ericntd** [comment]
Hi @mchuangatmp , I've found which looks like the fix for our problem https://github.com/mparticle-integrations/mparticle-android-integration-appsflyer/pull/57

May I know which release did it go into?
I've downloaded 5.47.2 and the decompiled code is still using non-null Bundle argument for `onActivityCreated`
![Screen Shot 2022-10-26 at 10 14 25 AM](https://user-images.githubusercontent.com/19919208/198050260-925fa037-bfa2-4459-8110-64db4f6ff1c4.png)
Is it possible for you to help release 5.45.3 containing https://github.com/mparticle-integrations/mparticle-android-integration-appsflyer/pull/57? 🙏 🙇

**Comment by jshin-tse** [comment]
@ericntd - Hey Eric, can you file a support ticket through our website? We do not use Github to resolve customer issues. Thank you

**Comment by ericntd** [comment]
I've done it @jshin-tse .
Hope this issue can resolve quickly 🙏 🙇 
It's been almost a week since it started.

**Comment by mchuangatmp** [comment]
Closing since issue was resolved in support ticket
